############## application properties ###############
spring:
  application:
    name: restservice
  thymeleaf:
    cache: false
    prefix: classpath:/templates           
  security:
   user:
    name: admin
    password: admin
    role: USER
   basic:
    enabled: false 
#  datasource:
#    url: jdbc:h2:mem:personas;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
############## Log properties ###############
logging:
  level:
    org.springframework.security: DEBUG
    com.woowrale.architecture.microservice: DEBUG
############## Server properties ###############
server:
  port: 8888
  tomcat:
    basedir: target/tomcat/
  servlet:
    contextPath: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true  
############## Springdoc properties ###############    
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /restservice/swagger-ui.html